export const CONSTANT_MSG = {
  INCIDENT_LIST_FAILED: "Failed to retrieve incidents",
  INVALID_ID: "Invalid ID",
  FILE_UPLOAD_FAILED: "File upload failed",
  INCIDENTS_RETRIEVED_SUCCESSFULLY: "Incidents retrieved successfully",
  INCIDENT_NOT_FOUND: "Incident not found",
  SUCCESS: "success",
  FAILED: "failed",
  OK: "ok",
  FILE_DELETED_SUCCESSFULLY: "File deleted successfully",
  FILE_ALREADY_DELETED: "File already deleted",
  FILE_DELETED_FAILED: "File deletion failed",
  ERROR_GETTING_ALL_INCIDENTS: "Error getting all incidents from microservice:",
  ERROR_GETTING_INCIDENT_BY_ID: "Error getting incident by ID:",
  ERROR_CREATING_INCIDENT: "Error creating incident:",
  ERROR_UPLODING_FILES: "Error uploading files:",
  GET_INCIDENT_BY_ID_SUCCESSFULLY: "Incident by ID retrieved successfully",
  INCIDENT_NOT_FOUND_BY_ID: "Incident not found by ID",
  CREATE_INCIDENT_SUCCESSFULLY: "Incident created successfully",
  CREAT_INCIDENT_FAILED: "Incident creation failed",
  ERROR_GETTING_INCIDENT_STATUS_COUNT: "Error getting incident status count:",
  GET_INCIDENT_COUNT_SUCCESS: "Incident count retrieved successfully",
  GET_INCIDENT_COUNT_FAILED: "Incident count retrieval failed:",
  CREATE_AUDIO_CONNECTION_FAILED: "Failed to create audio connection",
  ERROR_EXTRACTING_TEXT_FROM_AUDIO: "Error extracting text from audio: ",
};